#version: '3.8'

services:
  react:
    build:
      context: ./car_booking/frontend           # Le dossier contenant le code React
      dockerfile: ../../docker/react/Dockerfile_react  # Dockerfile situé dans docker/react/
    container_name: react_car_app
    ports:
      - "3000:3000"                              # Expose Vite sur le port 3000
    volumes:
      - ./car_booking/frontend:/app        
      -  /app/node_modules      # Synchronisation du code
    depends_on:
      - symfony                                  # Le frontend attend que le backend soit dispo

  symfony:
    build:
      context: ./car_booking/backend             # Dossier avec le code Symfony
      dockerfile: ../../docker/symfony/Dockerfile_symfony
    container_name: symfony_car_app
    ports:
      - "8000:8000"                              # Symfony exposé sur le port 8000
    volumes:
      - ./car_booking/backend:/app
     # -  /app/vendor      # Synchronisation du code
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/car_booking
    depends_on:
      - db                                       # Attente de MariaDB

  db:
    image: mariadb:10.7
    restart: always
    ports:
      - "3307:3306"                              # Accès local via 3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_booking
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"                                # PhpMyAdmin accessible sur localhost:8080
    environment:
      PMA_HOST: db
    depends_on:
      - db

  nginx:
    build:
      context: .                                 # Contexte à la racine du projet
      dockerfile: ./docker/nginx/Dockerfile_nginx
    container_name: nginx_car_app
    
    ports:
      - "80:80"                                  # Reverse proxy sur localhost
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - react
      - symfony

volumes:
  db_data:
